### ISSUE TITLE
在mac上build失败

### ISSUE THREAD

**Issue by luckypoem** [xsm1997/KumaSocks#1]
cd $GOPATH
go get -u -v github.com/xsm1997/KumaSocks/
显示：
...
github.com/xsm1997/KumaSocks
# github.com/xsm1997/KumaSocks
src/github.com/xsm1997/KumaSocks/main.go:69:18: undefined: GetOriginalDST
yudeMacBook-Air:gopath brite$ which KumaSocks
yudeMacBook-Air:gopath brite$ cd src/github.com/xsm1997/KumaSocks/
yudeMacBook-Air:KumaSocks brite$ ls
LICENSE			doc.go			main.go
README.md		kumasocks-sample.toml	original_dst_linux.go
yudeMacBook-Air:KumaSocks brite$ go build
# github.com/xsm1997/KumaSocks
./main.go:69:18: undefined: GetOriginalDST
yudeMacBook-Air:KumaSocks brite$ GOOS=darwin GOARCH=mipsle go build
cmd/go: unsupported GOOS/GOARCH pair darwin/mipsle
yudeMacBook-Air:KumaSocks brite$

怎么解决问题？

**Comment by xsm1997** [comment]
不支持在mac上使用，因为使用了linux专有的api

**Comment by xsm1997** [comment]
交叉编译请用GOOS=linux GOARCH=mipsle go build
